#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v20
# autospec commit: f35655a
#
# Source0 file verified with key 0x2C8DF587A6D4AAC1 (nicolas.fella@kde.org)
#
Name     : knotifications
Version  : 6.7.0
Release  : 89
URL      : https://download.kde.org/stable/frameworks/6.7/knotifications-6.7.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/6.7/knotifications-6.7.0.tar.xz
Source1  : https://download.kde.org/stable/frameworks/6.7/knotifications-6.7.0.tar.xz.sig
Source2  : 2C8DF587A6D4AAC1.pkey
Summary  : Abstraction for system notifications
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: knotifications-data = %{version}-%{release}
Requires: knotifications-lib = %{version}-%{release}
Requires: knotifications-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : libcanberra-dev
BuildRequires : pkgconfig(dbusmenu-qt5)
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# KNotification
Desktop notifications
## Introduction
KNotification is used to notify the user of an event. It covers feedback and
persistent events.

%package data
Summary: data components for the knotifications package.
Group: Data

%description data
data components for the knotifications package.


%package dev
Summary: dev components for the knotifications package.
Group: Development
Requires: knotifications-lib = %{version}-%{release}
Requires: knotifications-data = %{version}-%{release}
Provides: knotifications-devel = %{version}-%{release}
Requires: knotifications = %{version}-%{release}

%description dev
dev components for the knotifications package.


%package lib
Summary: lib components for the knotifications package.
Group: Libraries
Requires: knotifications-data = %{version}-%{release}
Requires: knotifications-license = %{version}-%{release}

%description lib
lib components for the knotifications package.


%package license
Summary: license components for the knotifications package.
Group: Default

%description license
license components for the knotifications package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 2C8DF587A6D4AAC1' gpg.status
%setup -q -n knotifications-6.7.0
cd %{_builddir}/knotifications-6.7.0
pushd ..
cp -a knotifications-6.7.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1728699682
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1728699682
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/knotifications
cp %{_builddir}/knotifications-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/knotifications/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/knotifications-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/knotifications/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/knotifications-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/knotifications/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/knotifications-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/knotifications/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/knotifications-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/knotifications/3c3d7573e137d48253731c975ecf90d74cfa9efe || :
cp %{_builddir}/knotifications-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/knotifications/757b86330df80f81143d5916b3e92b4bcb1b1890 || :
cp %{_builddir}/knotifications-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/knotifications/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/knotifications-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/knotifications/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/knotifications-%{version}/docs/qml-notification.md.license %{buildroot}/usr/share/package-licenses/knotifications/28ba3ebe1aa04fad742c69eb685e2a5376e9276f || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/locale/af/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ar/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/as/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ast/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/az/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/be/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/be@latin/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/bg/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/bn/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/bn_IN/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/br/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/bs/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ca/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/crh/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/cs/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/csb/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/cy/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/da/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/de/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/el/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/en_GB/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/eo/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/es/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/et/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/eu/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/fa/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/fi/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/fr/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/fy/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ga/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/gd/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/gl/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/gu/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ha/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/he/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/hi/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/hne/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/hr/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/hsb/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/hu/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/hy/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ia/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/id/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/is/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/it/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ja/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ka/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/kk/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/km/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/kn/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ko/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ku/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/lb/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/lt/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/lv/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/mai/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/mk/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ml/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/mr/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ms/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/nb/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/nds/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ne/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/nl/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/nn/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/oc/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/or/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/pa/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/pl/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ps/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/pt/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/pt_BR/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ro/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ru/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/se/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/si/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/sk/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/sl/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/sq/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/sr/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/sr@ijekavian/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/sr@ijekavianlatin/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/sr@latin/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/sv/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ta/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/te/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/tg/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/th/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/tr/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/tt/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/ug/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/uk/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/uz/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/uz@cyrillic/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/vi/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/wa/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/xh/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/zh_HK/LC_MESSAGES/knotifications6_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/knotifications6_qt.qm
/usr/share/qlogging-categories6/knotifications.categories
/usr/share/qlogging-categories6/knotifications.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/KF6/KNotifications/KNotification
/usr/include/KF6/KNotifications/KNotificationPermission
/usr/include/KF6/KNotifications/KNotificationReplyAction
/usr/include/KF6/KNotifications/KNotifyConfig
/usr/include/KF6/KNotifications/knotification.h
/usr/include/KF6/KNotifications/knotificationpermission.h
/usr/include/KF6/KNotifications/knotificationreplyaction.h
/usr/include/KF6/KNotifications/knotifications_export.h
/usr/include/KF6/KNotifications/knotifications_version.h
/usr/include/KF6/KNotifications/knotifyconfig.h
/usr/lib64/cmake/KF6Notifications/KF6NotificationsConfig.cmake
/usr/lib64/cmake/KF6Notifications/KF6NotificationsConfigVersion.cmake
/usr/lib64/cmake/KF6Notifications/KF6NotificationsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6Notifications/KF6NotificationsTargets.cmake
/usr/lib64/libKF6Notifications.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKF6Notifications.so.6.7.0
/V3/usr/lib64/qt6/qml/org/kde/notification/libknotificationqmlplugin.so
/usr/lib64/libKF6Notifications.so.6
/usr/lib64/libKF6Notifications.so.6.7.0
/usr/lib64/qt6/qml/org/kde/notification/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/notification/knotificationqmlplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/notification/libknotificationqmlplugin.so
/usr/lib64/qt6/qml/org/kde/notification/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/knotifications/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/knotifications/28ba3ebe1aa04fad742c69eb685e2a5376e9276f
/usr/share/package-licenses/knotifications/3c3d7573e137d48253731c975ecf90d74cfa9efe
/usr/share/package-licenses/knotifications/757b86330df80f81143d5916b3e92b4bcb1b1890
/usr/share/package-licenses/knotifications/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/knotifications/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/knotifications/e458941548e0864907e654fa2e192844ae90fc32
